config/routes.rb
Rails.application.routes.draw do
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :users
  resources :servicos
  resources :orcamentos
  resources :clientes
  resources :fornecedors
  resources :pecas
  resources :veiculos
  root 'sessions#new'


  get "/cliente/newj" => "clientes#newj", as: :new_clientej
  post "/orc_edit_user/:id" => "orcamentos#seta_user", as: :seta_user
  get "/orc_edit_desc/:id" => "orcamentos#seta_desc", as: :seta_desc

 #Status Orcamento
  post "status_orcamento/edit/:id" => "orcamentos#status_orcamento", as: :status_orcamento

  get "/estoque" => "estoque#index"
  post "/estoque/edit" => "estoque#salva"
  get "peca/teste" => "pecas#teste"
  
#Peças Orcamento
  get "/peca_orc/:id" => "peca_orc#index", as: :peca_orc
  post "/peca_orc/:id" => "peca_orc#inclui_peca", as: :inclui_peca
  delete "/peca_orc/:id" => "peca_orc#destroy"
  post "/peca_orc/edit/:id" => "peca_orc#edit", as: :peca_edit_orc 
  post "/serv_orc/edit/:id" => "servico_orc#edit", as: :serv_edit_orc 

#Servivo Orcamento
  post "/servico_orc/:id" => "servico_orc#inclui_servico", as: :inclui_servico
  delete "/servico_orc/:id" => "servico_orc#destroy", as: :delete_serv

#Relatorio
  get "/report/:id" => "report#orcamento", as: :report_orc

#Area do mecanico
  get "/oficina" => "oficina#index"

#buscas JS

  get "/busca_cliente/:id" => "clientes#busca_cliente_id", as: :pega_cliente_id
  get "/busca_cliente" => "clientes#busca_cliente", as: :pega_cliente

  get "/busca_pecas" => "pecas#busca_pecas", as: :pega_peca

  get "/busca_fornecedors" => "fornecedors#busca_fornecedors", as: :pega_fornecedors

#chama o modal edit peca orcamento
  get "/edit_peca_orc/:id" => "orcamentos#edit_peca_orc", as: :edit_peca_orc
  get "/edit_serv_orc/:id" => "orcamentos#edit_serv_orc", as: :edit_serv_orc

#chama modal edit status orcamento
  get "/status_orcamento/:id" => "orcamentos#status_orcamento_js", as: :status_orcamento_js

  get "/bucas_orcamento" => "orcamentos#busca_orcamento", as: :pega_orc

  get "/bucas_orcamento_status" => "orcamentos#busca_orcamento_status", as: :pega_orc_status


  get "/busca_veiculo" => "veiculos#busca_veiculo", as: :pega_veiculo


  #Dashboard
  get "/dashboard" => "dashboard#index"
    #chamada da table dashboard
  get "/dashboard_busca" => "dashboard#busca_orcamento", as: :busca_orc
    #chamada do menu para criar cliente
  get "/cliente/new_menu" => "clientes#new_menu", as: :new_cliente_menu
  post "/cliente" => "clientes#create_menu", as: :new_cliente2

  #Financeiro
  get "/financeiro" => "financeiro#index"

 
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :veiculo, :dependent => :destroy
	accepts_nested_attributes_for :veiculo, :allow_destroy => true 

	has_one :cliente_f
	accepts_nested_attributes_for :cliente_f, :allow_destroy => true 	

	has_one :cliente_j
	accepts_nested_attributes_for :cliente_j, :allow_destroy => true 	

	validates :celular, presence: true
	
	before_save {self.rua = rua.upcase}
	before_save {self.bairro = bairro.upcase}
	before_save {self.cidade = cidade.upcase}
	before_save {self.uf = uf.upcase}
	before_save {self.cep = cep.upcase}
	before_save {self.complemento = complemento.upcase}
	before_save {self.observacoes = observacoes.upcase}


end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new,:newj, :create,:show, :edit, :update, :destroy]

  # GET /clientes
  def index

  end

  # GET /clientes/1
  def show
  end

  def newj
    @cliente = Cliente.new
    @cliente.build_cliente_j
    @cliente.veiculo.build
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
    @cliente.build_cliente_f
    @cliente.veiculo.build
   end

  # GET /clientes/1/edit
  def edit

  end

  # POST /clientes
  def create
    c = nil
    n = 0
    if params[:cliente][:cliente_j_attributes] != nil
      n = 1
      c = cliente_params2
    else 
      n = 2
      c = cliente_params
    end
    @cliente = Cliente.new(c)
    km = params[:quilometragem]
    if @cliente.save
      if km != nil
      orc = Orcamento.new
      orc.cliente_id = Cliente.last.id
      orc.veiculo_id =  Veiculo.last.id 
      orc.valor_total = 0
      orc.quilometragem = km
      orc.status = params[:orcamento] [:status]
      orc.ocorrencia = params[:ocorrencia]
      orc.user_id = 0
      orc.save
      end
    redirect_to orc, notice: "Cadastro com sucesso"
    else
      if n == 1
        render :newj
      else
        render :new
      end
    end
  end


  # PATCH/PUT /clientes/1
  def update
    if @cliente.update(cliente_params)
      redirect_to @cliente, notice: 'Cliente editado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /clientes/1
  def destroy
    Veiculo.where(cliente_id: params["id"]).destroy_all 
    @cliente.destroy
    redirect_to clientes_url, notice: 'Cliente was successfully destroyed.'
  end

  def busca_cliente
   @selec =  params[:cli] [:selec]
   nome = params[:nome_c]
   if @selec == "Nome"
    @cliente_search = Cliente.joins "INNER JOIN cliente_fs on cliente_fs.cliente_id = clientes.id where cliente_fs.nome like '%#{nome}%'"
   elsif @selec == "Razao Social"
    @cliente_search = Cliente.joins "INNER JOIN cliente_js on cliente_js.cliente_id = clientes.id where cliente_js.razao_social like '%#{nome}%'"
   end
   #@cliente_search = Cliente.where "nome like ?", "%#{@nome}%"
    respond_to do |format|
      format.html 
      format.js
    end 
  end

def busca_cliente_id
  @cliente_search = Cliente.find(params[:id])
  respond_to do |format|
    format.html { render :edit }
    format.js 
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cliente_params
      params.require(:cliente).permit(:telefone, :celular, :comercial, :email, :observacoes,:rua, :numero, :bairro, :cidade, :uf, :cep, :complemento, :veiculo_attributes => [:placa, :marca, :modelo, :ano, :cor], :cliente_f_attributes => [:nome, :sobrenome, :cpf, :rg, :sexo, :oficio, :id])
    end

    def cliente_params2
      params.require(:cliente).permit(:telefone, :celular, :comercial, :email, :observacoes,:rua, :numero, :bairro, :cidade, :uf, :cep, :complemento, :veiculo_attributes => [:placa, :marca, :modelo, :ano, :cor], :cliente_j_attributes => [:razao_social, :nome_fantasia, :cnpj, :representante, :id])
    end
    

end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :cliente_nome %>
  </div>

  <div class="field">
    <%= form.label :oficio %>
    <%= form.text_field :oficio, id: :cliente_oficio %>
  </div>

  <div class="field">
    <%= form.label :rua %>
    <%= form.text_field :rua, id: :cliente_rua %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :cliente_bairro %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :cliente_cidade %>
  </div>

  <div class="field">
    <%= form.label :uf %>
    <%= form.text_field :uf, id: :cliente_uf %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep, id: :cliente_cep %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :cliente_telefone %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular, id: :cliente_celular %>
  </div>

  <div class="field">
    <%= form.label :comercial %>
    <%= form.text_field :comercial, id: :cliente_comercial %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :cliente_email %>
  </div>

  <div class="field">
    <%= form.label :observacoes %>
    <%= form.text_field :observacoes, id: :cliente_observacoes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/_formCV.html.erb
<%= form_with(model: cliente, local: true) do |form| %>

  <% if cliente.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <div class="alert alert-error"><%= message %></div>
      <% end %>
      </ul>
    </div>

  <% end %>
 <div class="leftcontact">

<%= form.fields_for(:cliente_f) do |fe|%>

  <div class="form-group">
    <%= fe.label "Nome" %>
    <%= fe.text_field :nome, id: :cliente_f_nome %>
  </div>

  <div class="form-group">
    <%= fe.label :sobrenome %>
    <%= fe.text_field :sobrenome, id: :cliente_sobrenome %>
  </div>

  <div class="form-group">
    <label>CPF</label>
    <%= fe.text_field :cpf, id: :cliente_cpf %>
  </div>

  <div class="form-group">
    <label>RG</label>
    <%= fe.text_field :rg, id: :cliente_rg %>
  </div>

  <div class="form-group form-inline">
    <%= fe.label :M %>
    <%= fe.radio_button :sexo, 'M'%>
    <p>    </p>
    <%= fe.label :F %>
    <%= fe.radio_button :sexo, 'F'%>

  </div>

  <div class="form-group">
    <%= fe.label "Ofício" %>
    <%= fe.text_field :oficio, id: :cliente_oficio %>
  </div>
 
  <%end%>

  <div class="form-group">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :cliente_telefone %>
  </div>

  <div class="form-group">
    <%= form.label :celular %>
    <%= form.text_field :celular, id: :cliente_celular %>
  </div>

  <div class="form-group">
    <%= form.label :comercial %>
    <%= form.text_field :comercial, id: :cliente_comercial %>
  </div>

  <div class="form-group">
    <%= form.label "E-mail" %>
    <%= form.text_field :email, id: :cliente_email %>
  </div>

  <div class="form-group">
    <label>Observações</label>
    <%= form.text_field :observacoes, id: :cliente_observacoes %>
  </div>

  <div class="form-group">
    <label>CEP</label>
    <%= form.text_field :cep, id: :endereco_cep %>
  </div>

  <div class="form-group">
    <%= form.label :rua %>
    <%= form.text_field :rua, id: :endereco_rua %>
  </div>
  
  <div class="form-group">
    <%= form.label :número %>
    <%= form.text_field :numero, id: :endereco_numero %>
  </div>

  <div class="form-group">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :endereco_bairro %>
  </div>

  <div class="form-group">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :endereco_cidade %>
  </div>

  <div class="form-group">
    <label>UF</label>
    <%= form.text_field :uf, id: :endereco_uf %>
  </div>


  <div class="form-group">
    <%= form.label :complemento %>
    <%= form.text_field :complemento, id: :endereco_complemento %>
  </div>


  </div>

  <div class="rightcontact">
    <%= form.fields_for(:veiculo) do |ff|%>

    <div class="field">
    <%= ff.label :placa %>
    <%= ff.text_field :placa, id: :veiculo_placa %>
  </div>

  <div class="field">
    <%= ff.label :marca %>
<%= ff.select(:marca, ['Acura','Agrale','Alfa Romeo','AM Gen','Asia Motors','ASTON MARTIN','Audi','BMW','BRM','Buggy','Bugre','Cadillac','CBT Jipe','CHANA','CHANGAN','CHERY','Chrysler','Citroen','Cross Lander','Daewoo','Daihatsu','Dodge','EFFA','Engesa','Envemo','Ferrari','Fiat','Fibravan','Ford','FOTON','Fyber','GEELY','GM - Chevrolet','GREAT WALL','Gurgel','HAFEI','Honda','Hyundai','Isuzu','JAC','Jaguar','Jeep','JINBEI','JPX','Kia Motors','Lada','LAMBORGHINI','Land Rover','Lexus','LIFAN','LOBINI','Lotus','Mahindra','Maserati','Matra','Mazda','Mercedes-Benz','Mercury','MG','MINI','Mitsubishi','Miura','Nissan','Peugeot','Plymouth','Pontiac','Porsche','RAM','RELY','Renault','Rolls-Royce','Rover','Saab','Saturn','Seat','SHINERAY','smart','SSANGYONG','Subaru','Suzuki','TAC', 'Toyota','Troller','Volvo','VW - VolksWagen','Dafra','Honda','Kawasaki']) %>  
</div>

  <div class="field">
    <%= ff.label :modelo %>
    <%= ff.text_field :modelo, id: :veiculo_modelo %>
  </div>

  <div class="field">
    <%= ff.label :ano %>
    <%= ff.text_field :ano, id: :veiculo_ano %>
  </div>

  <div class="field">
    <%= ff.label :cor %>
    <%= ff.text_field :cor, id: :veiculo_cor %>
  </div>

    <%end%>

    <div class="form-inline">
    <input type="checkbox" id="orc_check" value="yes" onchange="muda(this, 'quilometragem');">
  Selecione para criar orçamento
  </div>
  </br>

  <div class="field">
    <%= label_tag :quilometragem %>
    <%= text_field_tag :quilometragem,"",disabled: true %>
  </div>

  <div class="field">
    <%= form.label :Status %>
    <%= select(:orcamento, :status,[ '1. Análise','2. Aguardando Cotação','3. Aguardando Aprovação', '4. Reprovado', '5. Aprovado', '6. Aguardando Fornecedor','7. Em manutenção', '8. Teste', '9. Finalizado', '10. Aguardando Pagamento'])%>
  </div>

 <div class="field">
    <%= label_tag :ocorrência %>
    <%= text_area_tag :ocorrencia, nil, rows: 10, cols: 25 %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar" %>
  </div>
</div>


<% end %>

app/views/clientes/_formCVC.html.erb
<%= form_with(model: cliente, local: true) do |form| %>

  <% if cliente.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <div class="alert alert-error"><%= message %></div>
      <% end %>
      </ul>
    </div>

  <% end %>

<%= form.fields_for(:cliente_f) do |fe|%>

  <div class="form-group">
    <%= fe.label :nome %>
    <%= fe.text_field :nome, id: :cliente_f_nome %>
  </div>

  <div class="form-group">
    <%= fe.label :sobrenome %>
    <%= fe.text_field :sobrenome, id: :cliente_sobrenome %>
  </div>

  <div class="form-group">
    <%= fe.label :cpf %>
    <%= fe.text_field :cpf, id: :cliente_cpf %>
  </div>

  <div class="form-group">
    <%= fe.label :rg %>
    <%= fe.text_field :rg, id: :cliente_rg %>
  </div>

    <div class="form-group form-inline">
    <%= fe.label :M %>
    <%= fe.radio_button :sexo, 'M'%>
    <p>    </p>
    <%= fe.label :F %>
    <%= fe.radio_button :sexo, 'F'%>

  </div>

  <div class="form-group">
    <%= fe.label :oficio %>
    <%= fe.text_field :oficio, id: :cliente_oficio %>
  </div>
 
  <%end%>

  <div class="form-group">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :cliente_telefone %>
  </div>

  <div class="form-group">
    <%= form.label :celular %>
    <%= form.text_field :celular, id: :cliente_celular %>
  </div>

  <div class="form-group">
    <%= form.label :comercial %>
    <%= form.text_field :comercial, id: :cliente_comercial %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :cliente_email %>
  </div>

  <div class="form-group">
    <%= form.label :observacoes %>
    <%= form.text_field :observacoes, id: :cliente_observacoes %>
  </div>


  <div class="form-group">
    <%= form.label :rua %>
    <%= form.text_field :rua, id: :endereco_rua %>
  </div>
  
  <div class="form-group">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: :endereco_numero %>
  </div>

  <div class="form-group">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :endereco_bairro %>
  </div>

  <div class="form-group">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :endereco_cidade %>
  </div>

  <div class="form-group">
    <%= form.label :uf %>
    <%= form.text_field :uf, id: :endereco_uf %>
  </div>

  <div class="form-group">
    <%= form.label :cep %>
    <%= form.text_field :cep, id: :endereco_cep %>
  </div>

  <div class="form-group">
    <%= form.label :complemento %>
    <%= form.text_field :complemento, id: :endereco_complemento %>
  </div>


  <div class="actions">
    <%= form.submit "Cadastrar" %>
  </div>
</div>


<% end %>

app/views/clientes/_formJ.html.erb

	<%= form_with(model: cliente, local: true) do |form| %>

  <% if @cliente.errors.any? %>
    <div id="error_explanation">

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <div class="alert alert-error"><%= message %></div>
      <% end %>
      </ul>
    </div>

  <% end %>

<%= form.fields_for(:cliente_j) do |fe|%>

  <div class="form-group">
    <%= fe.label :razao_social %><span>*</span>
    <span class="icon-case"><i class="fa fa-user"></i></span>
    <%= fe.text_field :razao_social, id: :cliente_razao_social %>
  </div>

  <div class="form-group">
    <%= fe.label :nome_fantasia %>
    <%= fe.text_field :nome_fantasia, id: :cliente_nome_fantasia %>
  </div>

  <div class="form-group">
    <%= fe.label :cnpj %>
    <%= fe.text_field :cnpj, id: :cliente_cnpj%>
  </div>

  <div class="form-group">
    <%= fe.label :representante %>
    <%= fe.text_field :representante, id: :cliente_representante %>
  </div>

 
  <%end%>

  <div class="form-group">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :cliente_telefone %>
  </div>

  <div class="form-group">
    <%= form.label :celular %>
    <%= form.text_field :celular, id: :cliente_celular %>
  </div>

  <div class="form-group">
    <%= form.label :comercial %>
    <%= form.text_field :comercial, id: :cliente_comercial %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :cliente_email %>
  </div>

  <div class="form-group">
    <%= form.label :observacoes %>
    <%= form.text_field :observacoes, id: :cliente_observacoes %>
  </div>


  <div class="form-group">
    <%= form.label :rua %>
    <%= form.text_field :rua, id: :endereco_rua %>
  </div>
  
  <div class="form-group">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: :endereco_numero %>
  </div>

  <div class="form-group">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :endereco_bairro %>
  </div>

  <div class="form-group">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :endereco_cidade %>
  </div>

  <div class="form-group">
    <%= form.label :uf %>
    <%= form.text_field :uf, id: :endereco_uf %>
  </div>

  <div class="form-group">
    <%= form.label :cep %>
    <%= form.text_field :cep, id: :endereco_cep %>
  </div>

  <div class="form-group">
    <%= form.label :complemento %>
    <%= form.text_field :complemento, id: :endereco_complemento %>
  </div>



  <div class="actions">
    <%= form.submit "Cadastrar" %>
  </div>
</div>


<% end %>

app/views/clientes/_tabela_cliente.html.erb
  <% clientes.each do |cliente| %>
      <tr>
        <td class="span3">
        <% if cliente.cliente_f != nil %>
        <%= cliente.cliente_f.nome %> <%= cliente.cliente_f.sobrenome %>
        <%else%>
        <%= cliente.cliente_j.razao_social %>
        <%end%>
        </td>
        <td class="span3"><%= cliente.telefone %></td>
        <td class="span3"><%= cliente.celular %></td>
        <td class="span3"><%= cliente.email %></td>
        <td class="span3"><%= cliente.observacoes %>
        <td class="span3">
        <div class="btn-group">
        <button class="btn ">Funçoes</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">

        <%= link_to 'Exibir', cliente %>
        <%= link_to 'Editar', edit_cliente_path(cliente) %>
        <%= link_to 'Deletar', cliente, method: :delete, data: { confirm: 'Tem certeza? isso ira deletar todos os carros relacionado' } %>
          
      </ul>
      </div>

        </td>
      </tr>
    <% end %>

app/views/clientes/busca_cliente.js.erb
<%if @selec == "Nome"%>
	$('table#cliente tbody').html("<%= j render 'clientes/table/tabela_cliente', clientes: @cliente_search %>");
	$('table#veiculo tbody').html("<%= j render 'clientes/table/table_cliente_newVeiculo', clientes: @cliente_search %>");
	$('table#table_new_orc tbody').html("<%= j render 'clientes/table/table_orcamento_cliente', cliente_orc: @cliente_search %>");
<% elsif @selec == "Razao Social"%>
	$('table#cliente tbody').html("<%= j render 'clientes/table/tabela_clienteR', clientes: @cliente_search %>");
	$('table#veiculo tbody').html("<%= j render 'clientes/table/table_clienteR_newVeiculo', clientes: @cliente_search %>");
	$('table#table_new_orc tbody').html("<%= j render 'clientes/table/table_orcamento_clienteR', cliente_orc: @cliente_search %>");
<%end%>

app/views/clientes/busca_cliente_id.js.erb
$('table#veiculo_orc tbody').html("<%= j render 'clientes/table/tabela_veiculo_cliente', clientes: @cliente_search %>")

app/views/clientes/edit.html.erb
<div class="span6">
<h3>Editar Cliente</h3>

	<% if @cliente.cliente_f != nil %>
	    <%= render 'formCVC', cliente: @cliente %>
	<%else%>
		<%= render 'formJ', cliente: @cliente %>
	<%end%>

</div>

app/views/clientes/index.html.erb
<div class="span16">

<%= link_to 'Novo Cliente Físico', new_cliente_path, class: "btn btn-primary" %>

<%= link_to 'Novo Cliente Jurídico', new_clientej_path, class: "btn btn-primary" %>

<br>
<p id="notice"><%= notice %></p>
<div class="box pattern pattern-sandstone">

    <div class="box-header">
       <i class="icon-table"></i>
        <h5>
        Clientes
        </h5>
    </div>

    <div class="box-content">
    <div class="row">
    <div class="span15">
<%= form_tag(pega_cliente_path, method: :get, :remote => true) do %>
          <div class="form-inline">
          <%= select(:cli, :selec, [ 'Nome','Razão Social']) %> 
          <%= label_tag :nome %>
          <%= text_field_tag :nome_c %>
          <%= submit_tag "Encontrar"%>
          </div>
          <% end %>
<table id="cliente">
  <thead>
    <tr>
      <th class="span3">Nome</th>
      <th class="span3">Telefone</th>
      <th class="span3">Celular</th>
      <th class="span3">E-mail</th>
      <th class="span3">Observações</th>
      <th class="span3"></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>
</div>
</div>
</div>
</div>
</div>

app/views/clientes/new.html.erb
		<div class="span16">
       		<%= render 'formCV', cliente: @cliente %>
       
		</div>

app/views/clientes/show.html.erb
<div class="span16">
<p id="notice"><%= notice %></p>

<% if @cliente.cliente_f != nil %>

<p>
  <strong>Nome:</strong>
  <%= @cliente.cliente_f.nome %> <%=@cliente.cliente_f.sobrenome%>
</p>

<p>
  <strong>CPF:</strong>
  <%= @cliente.cliente_f.cpf %>
</p>

<p>
  <strong>RG:</strong>
  <%= @cliente.cliente_f.rg %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @cliente.cliente_f.sexo %>
</p>


<p>
  <strong>Oficio:</strong>
  <%= @cliente.cliente_f.oficio %>
</p>


  <%else%>
<p>
  <strong>Razão Social:</strong>
  <%= @cliente.cliente_j.razao_social %>
</p>

<p>
  <strong>Nome Fantasia:</strong>
  <%= @cliente.cliente_j.nome_fantasia %>
</p>

<p>
  <strong>Representante:</strong>
  <%= @cliente.cliente_j.representante %>
</p>

<p>
  <strong>CNPJ:</strong>
  <%= @cliente.cliente_j.cnpj %>
</p>

  <%end%>


<p>
  <strong>Rua:</strong>
  <%= @cliente.rua %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @cliente.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @cliente.cidade %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @cliente.uf %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @cliente.cep %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @cliente.celular %>
</p>

<p>
  <strong>Comercial:</strong>
  <%= @cliente.comercial %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Observacoes:</strong>
  <%= @cliente.observacoes %>
</p>
</div>