config/routes.rb
Rails.application.routes.draw do
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :users
  resources :servicos
  resources :orcamentos
  resources :clientes
  resources :fornecedors
  resources :pecas
  resources :veiculos
  root 'sessions#new'


  get "/cliente/newj" => "clientes#newj", as: :new_clientej
  post "/orc_edit_user/:id" => "orcamentos#seta_user", as: :seta_user
  get "/orc_edit_desc/:id" => "orcamentos#seta_desc", as: :seta_desc

 #Status Orcamento
  post "status_orcamento/edit/:id" => "orcamentos#status_orcamento", as: :status_orcamento

  get "/estoque" => "estoque#index"
  post "/estoque/edit" => "estoque#salva"
  get "peca/teste" => "pecas#teste"
  
#Peças Orcamento
  get "/peca_orc/:id" => "peca_orc#index", as: :peca_orc
  post "/peca_orc/:id" => "peca_orc#inclui_peca", as: :inclui_peca
  delete "/peca_orc/:id" => "peca_orc#destroy"
  post "/peca_orc/edit/:id" => "peca_orc#edit", as: :peca_edit_orc 
  post "/serv_orc/edit/:id" => "servico_orc#edit", as: :serv_edit_orc 

#Servivo Orcamento
  post "/servico_orc/:id" => "servico_orc#inclui_servico", as: :inclui_servico
  delete "/servico_orc/:id" => "servico_orc#destroy", as: :delete_serv

#Relatorio
  get "/report/:id" => "report#orcamento", as: :report_orc

#Area do mecanico
  get "/oficina" => "oficina#index"

#buscas JS

  get "/busca_cliente/:id" => "clientes#busca_cliente_id", as: :pega_cliente_id
  get "/busca_cliente" => "clientes#busca_cliente", as: :pega_cliente

  get "/busca_pecas" => "pecas#busca_pecas", as: :pega_peca

  get "/busca_fornecedors" => "fornecedors#busca_fornecedors", as: :pega_fornecedors

#chama o modal edit peca orcamento
  get "/edit_peca_orc/:id" => "orcamentos#edit_peca_orc", as: :edit_peca_orc
  get "/edit_serv_orc/:id" => "orcamentos#edit_serv_orc", as: :edit_serv_orc

#chama modal edit status orcamento
  get "/status_orcamento/:id" => "orcamentos#status_orcamento_js", as: :status_orcamento_js

  get "/bucas_orcamento" => "orcamentos#busca_orcamento", as: :pega_orc

  get "/bucas_orcamento_status" => "orcamentos#busca_orcamento_status", as: :pega_orc_status


  get "/busca_veiculo" => "veiculos#busca_veiculo", as: :pega_veiculo


  #Dashboard
  get "/dashboard" => "dashboard#index"
    #chamada da table dashboard
  get "/dashboard_busca" => "dashboard#busca_orcamento", as: :busca_orc
    #chamada do menu para criar cliente
  get "/cliente/new_menu" => "clientes#new_menu", as: :new_cliente_menu
  post "/cliente" => "clientes#create_menu", as: :new_cliente2

  #Financeiro
  get "/financeiro" => "financeiro#index"

 
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :veiculo, :dependent => :destroy
	accepts_nested_attributes_for :veiculo, :allow_destroy => true 

	has_one :cliente_f
	accepts_nested_attributes_for :cliente_f, :allow_destroy => true 	

	has_one :cliente_j
	accepts_nested_attributes_for :cliente_j, :allow_destroy => true 	

	validates :celular, presence: true
	
	before_save {self.rua = rua.upcase}
	before_save {self.bairro = bairro.upcase}
	before_save {self.cidade = cidade.upcase}
	before_save {self.uf = uf.upcase}
	before_save {self.cep = cep.upcase}
	before_save {self.complemento = complemento.upcase}
	before_save {self.observacoes = observacoes.upcase}


end

app/models/cliente_f.rb
class ClienteF < ApplicationRecord
  belongs_to :cliente


	before_save {self.nome = nome.upcase}
	before_save {self.sobrenome = sobrenome.upcase}
	before_save {self.oficio = oficio.upcase}
	before_save {self.sexo = sexo.upcase}
	
end

app/models/cliente_j.rb
class ClienteJ < ApplicationRecord
	  belongs_to :cliente

	before_save {self.razao_social = razao_social.upcase}
	before_save {self.nome_fantasia = nome_fantasia.upcase}
	before_save {self.representante = representante.upcase}

end

app/models/estoque.rb
class Estoque < ApplicationRecord
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord

	before_save {self.rua = rua.upcase}
	before_save {self.bairro = bairro.upcase}
	before_save {self.cidade = cidade.upcase}
	before_save {self.uf = uf.upcase}
	before_save {self.cep = cep.upcase}
	before_save {self.complemento = complemento.upcase}
	before_save {self.nome_fornecedor = nome_fornecedor.upcase}
	before_save {self.ramo = ramo.upcase}
	before_save {self.vendedor = vendedor.upcase}

end

app/models/orcamento.rb
class Orcamento < ApplicationRecord
  belongs_to :cliente
  belongs_to :veiculo
  belongs_to :user

  has_many :peca_orc
  has_many :peca, through: :peca_orc

  has_many :servico_orc
  has_many :servico, through: :servico_orc

  validates :status, presence: true
  validates :quilometragem, presence: true
  validates :user_id, presence: false
 
end

app/models/peca.rb
class Peca < ApplicationRecord
	belongs_to :fornecedor

	has_many :peca_orc
	has_many :orcamento, through: :peca_orc

	before_save {self.nome = nome.upcase}
	before_save {self.tipo = tipo.upcase}
	before_save {self.fabricante = fabricante.upcase}
	before_save {self.marca_carro = marca_carro.upcase}
	before_save {self.modelo_carro = modelo_carro.upcase}

end

app/models/peca_orc.rb
class PecaOrc < ApplicationRecord
  belongs_to :orcamento
  belongs_to :peca
end

app/models/servico.rb
class Servico < ApplicationRecord

	has_many :peca_orc
	has_many :orcamento, through: :peca_orc

	before_save {self.nome = nome.upcase}
    before_save {self.descricao = descricao.upcase}



end

app/models/servico_orc.rb
class ServicoOrc < ApplicationRecord
  belongs_to :servico
  belongs_to :orcamento
end

app/models/user.rb
class User < ApplicationRecord
	  has_secure_password
  #validates name, presence: true, length: {maximum: 50}
  #validates password_digest, presence: true, length: {minimum: 6}
  VALID_LOGIN_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  #validates login, presence: true, length: {maximum: 260}, uniqueness: {case_sensitive: false}
  #before_save { self.login = login.downcase }
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :cliente, optional: true

  validates :marca, presence: true
  validates :modelo, presence: true
  validates :placa, presence: true
  validates :ano, presence: true

 	before_save { self.marca = marca.upcase }
	before_save {self.modelo = modelo.upcase}
	before_save {self.cor = cor.upcase}

end

app/controllers/pecas_controller.rb
class PecasController < ApplicationController
  before_action :set_peca, only: [:show, :edit, :update, :destroy]

  # GET /pecas
  def index
    Peca.new
    @pecas = Peca.all
  end

  def busca_pecas
   @nome = params[:nome_p]
   @peca_search = Peca.where "nome like ?", "%#{@nome}%"
   puts @peca_search
    respond_to do |format|
      format.html 
      format.js
    end 
  end

  # GET /pecas/1
  def show
  end

  # GET /pecas/new
  def new
    @peca = Peca.new
    @fornecedors = Fornecedor.all
  end

  # GET /pecas/1/edit
  def edit
        @fornecedors = Fornecedor.all
  end

  # POST /pecas
  def create
    @peca = Peca.new(peca_params)

    if @peca.save
      redirect_to pecas_path, notice: 'Peça Criada Com Sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /pecas/1
  def update
    if @peca.update(peca_params)
      redirect_to pecas_path, notice: 'Peça Editada Com Sucesso.'
    else
      render :edit
    end
  end

  # DELETE /pecas/1
  def destroy
    @peca.destroy
    redirect_to pecas_url, notice: 'Peça Deletada Com Sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peca
      @peca = Peca.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def peca_params
      params.require(:peca).permit(:nome, :tipo, :fabricante, :preco, :marca_carro, :modelo_carro, :fornecedor_id)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/estoque_helper.rb
module EstoqueHelper
end

app/helpers/oficina_helper.rb
module OficinaHelper
end

app/helpers/peca_orc_helper.rb
module PecaOrcHelper
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
     session[:user_id] = user.id
  end

   def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def block_access
    if current_user.present?
     redirect_to users_path
   end
  end

    def logged_in?
    !current_user.nil?
    end

    def sign_out
     session.delete(:user_id)
     @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/pecas/_form.html.erb
<div class="span16">
<%= form_with(model: peca, local: true) do |form| %>
  <% if peca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peca.errors.count, "error") %> prohibited this peca from being saved:</h2>

      <ul>
      <% peca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :peca_nome %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :peca_tipo %>
  </div>

  <div class="field">
    <%= form.label :fabricante %>
    <%= form.text_field :fabricante, id: :peca_fabricante %>
  </div>

    <div class="field">
    <%= form.label "Marca Veículo"%>
    <%= form.select(:marca_carro, ['Acura','Agrale','Alfa Romeo','AM Gen','Asia Motors','ASTON MARTIN','Audi','BMW','BRM','Buggy','Bugre','Cadillac','CBT Jipe','CHANA','CHANGAN','CHERY','Chrysler','Citroen','Cross Lander','Daewoo','Daihatsu','Dodge','EFFA','Engesa','Envemo','Ferrari','Fiat','Fibravan','Ford','FOTON','Fyber','GEELY','GM - Chevrolet','GREAT WALL','Gurgel','HAFEI','Honda','Hyundai','Isuzu','JAC','Jaguar','Jeep','JINBEI','JPX','Kia Motors','Lada','LAMBORGHINI','Land Rover','Lexus','LIFAN','LOBINI','Lotus','Mahindra','Maserati','Matra','Mazda','Mercedes-Benz','Mercury','MG','MINI','Mitsubishi','Miura','Nissan','Peugeot','Plymouth','Pontiac','Porsche','RAM','RELY','Renault','Rolls-Royce','Rover','Saab','Saturn','Seat','SHINERAY','smart','SSANGYONG','Subaru','Suzuki','TAC', 'Toyota','Troller','Volvo','VW - VolksWagen','Dafra','Honda','Kawasaki']) %>  
    </div>

  <div class="field">
     <%= form.label "Modelo Veículo"%>
    <%= form.text_field :modelo_carro, id: :peca_modelo %>
  </div>

  <div class="field">
    <%= form.label :preço %>
    <%= form.text_field :preco, id: :peca_preco %>
  </div>

  <div class="field">
    <%= form.label :fornecedores %>
    <%= form.collection_select :fornecedor_id, @fornecedors, :id, :nome_fornecedor %>
  </div>

  <div class="actions">
      <%= form.submit "Cadastrar", class:"btn btn-default"  %>

  </div>
<% end %>
</div>

app/views/pecas/_tabela_peca.html.erb
    <% pecas_orc.each do |peca| %>
                <tr>
                <td class="span3"><%= peca.nome %></td>
                <td class="span3"><%= peca.tipo %></td>
                <td class="span3"><%= peca.fabricante %></td>
                <td class="span2"><%= peca.preco %></td>
                <td class="span2"><%= radio_button_tag :peca_id, peca.id %></td>
              </tr>
   <% end %>

app/views/pecas/_table_orc_pecas.html.erb
<% if logged_in? %>
<%end%>
  <%if @current_user.cargo == "mecanico"%>
    <% pecas_orc.each do |peca| %>
                <tr>
                <td class="span3"><%= peca.nome %></td>
                <td class="span3"><%= peca.tipo %></td>
                <td class="span3"><%= peca.fabricante %></td>
                <td class="span2"><%= radio_button_tag :peca_id, peca.id %></td>
              </tr>
   <% end %>
  <%else%>
    <% pecas_orc.each do |peca| %>
                <tr>
                <td class="span3"><%= peca.nome %></td>
                <td class="span3"><%= peca.tipo %></td>
                <td class="span3"><%= peca.fabricante %></td>
                <td class="span2">R$<%= peca.preco %></td>
                <td class="span2"><%= radio_button_tag :peca_id, peca.id %></td>
              </tr>
   <% end %>
  <%end%>

app/views/pecas/busca_pecas.js.erb
$('table#table_orc_pecas tbody').html("<%= j render 'pecas/table_orc_pecas', pecas_orc: @peca_search %>")
$('table#pecas_index tbody').html("<%= j render 'pecas/table/pecas_index', pecas: @peca_search %>")

app/views/pecas/edit.html.erb
<h1>Editar Peça</h1>

<%= render 'form', peca: @peca %>

<%= link_to 'Exibir', @peca, class:"btn btn-primary" %> |
<%= link_to 'Voltar', pecas_path, class:"btn btn-primary" %>

app/views/pecas/index.html.erb
<div class="span16">
<%= link_to 'Nova Peça', new_peca_path, class:"btn btn-primary margin-form" %>
<p id="notice"><%= notice %></p>

<div class="box pattern pattern-sandstone">

    <div class="box-header">
       <i class="icon-table"></i>
        <h5>
          Peças
        </h5>
    </div>

    <div class="box-content">
    <div class="row">
    <div class="span15">


      <%= form_tag(pega_peca_path, method: :get, :remote => true) do %>
          <div class="form-inline"> 
          <%= label_tag :nome %>
          <%= text_field_tag :nome_p %>
          <%= submit_tag "Encontrar"%>
          </div>
          <% end %>

  <table id="pecas_index" class="table">
  <thead>
    <tr>
      <th class="span3"></th>
      <th class="span3">Nome</th>
      <th class="span3">Tipo</th>
      <th class="span3">Fabricante</th>
      <th class="span3">Preço</th>
      <th class="span3">Marca</th>
      <th class="span3" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
  </tbody>
</table>
</div>
</div>
</div>
</div>

<br>

</div>

app/views/pecas/new.html.erb
<div class="container">
       <div class="row">
         <div id="acct-password-row" class="span5">
           <fieldset>
             <legend>Cadastro de Peças</legend><br>
				<%= render 'form', peca: @peca %>
				<%= link_to 'Novo Fonecedor', new_fornecedor_path, class:"btn btn-default" %>

			</fieldset>

		</div>
	  </div>
   </div>

app/views/pecas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @peca.nome %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @peca.tipo %>
</p>

<p>
  <strong>Fabricante:</strong>
  <%= @peca.fabricante %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @peca.preco %>
</p>

<%= link_to 'Editar', edit_peca_path(@peca) %> |
<%= link_to 'Voltar', pecas_path, data: { keybinding: 'q' }%>