config/routes.rb
Rails.application.routes.draw do
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :users
  resources :servicos
  resources :orcamentos
  resources :clientes
  resources :fornecedors
  resources :pecas
  resources :veiculos
  root 'sessions#new'


  get "/cliente/newj" => "clientes#newj", as: :new_clientej
  post "/orc_edit_user/:id" => "orcamentos#seta_user", as: :seta_user
  get "/orc_edit_desc/:id" => "orcamentos#seta_desc", as: :seta_desc

 #Status Orcamento
  post "status_orcamento/edit/:id" => "orcamentos#status_orcamento", as: :status_orcamento

  get "/estoque" => "estoque#index"
  post "/estoque/edit" => "estoque#salva"
  get "peca/teste" => "pecas#teste"
  
#Peças Orcamento
  get "/peca_orc/:id" => "peca_orc#index", as: :peca_orc
  post "/peca_orc/:id" => "peca_orc#inclui_peca", as: :inclui_peca
  delete "/peca_orc/:id" => "peca_orc#destroy"
  post "/peca_orc/edit/:id" => "peca_orc#edit", as: :peca_edit_orc 
  post "/serv_orc/edit/:id" => "servico_orc#edit", as: :serv_edit_orc 

#Servivo Orcamento
  post "/servico_orc/:id" => "servico_orc#inclui_servico", as: :inclui_servico
  delete "/servico_orc/:id" => "servico_orc#destroy", as: :delete_serv

#Relatorio
  get "/report/:id" => "report#orcamento", as: :report_orc

#Area do mecanico
  get "/oficina" => "oficina#index"

#buscas JS

  get "/busca_cliente/:id" => "clientes#busca_cliente_id", as: :pega_cliente_id
  get "/busca_cliente" => "clientes#busca_cliente", as: :pega_cliente

  get "/busca_pecas" => "pecas#busca_pecas", as: :pega_peca

  get "/busca_fornecedors" => "fornecedors#busca_fornecedors", as: :pega_fornecedors

#chama o modal edit peca orcamento
  get "/edit_peca_orc/:id" => "orcamentos#edit_peca_orc", as: :edit_peca_orc
  get "/edit_serv_orc/:id" => "orcamentos#edit_serv_orc", as: :edit_serv_orc

#chama modal edit status orcamento
  get "/status_orcamento/:id" => "orcamentos#status_orcamento_js", as: :status_orcamento_js

  get "/bucas_orcamento" => "orcamentos#busca_orcamento", as: :pega_orc

  get "/bucas_orcamento_status" => "orcamentos#busca_orcamento_status", as: :pega_orc_status


  get "/busca_veiculo" => "veiculos#busca_veiculo", as: :pega_veiculo


  #Dashboard
  get "/dashboard" => "dashboard#index"
    #chamada da table dashboard
  get "/dashboard_busca" => "dashboard#busca_orcamento", as: :busca_orc
    #chamada do menu para criar cliente
  get "/cliente/new_menu" => "clientes#new_menu", as: :new_cliente_menu
  post "/cliente" => "clientes#create_menu", as: :new_cliente2

  #Financeiro
  get "/financeiro" => "financeiro#index"

 
end

app/models/orcamento.rb
class Orcamento < ApplicationRecord
  belongs_to :cliente
  belongs_to :veiculo
  belongs_to :user

  has_many :peca_orc
  has_many :peca, through: :peca_orc

  has_many :servico_orc
  has_many :servico, through: :servico_orc

  validates :status, presence: true
  validates :quilometragem, presence: true
  validates :user_id, presence: false
 
end

app/controllers/orcamentos_controller.rb
class OrcamentosController < ApplicationController
  before_action :set_orcamento, only: [:show, :edit, :update, :destroy]
  #before_action :authorize, except: [:create,:show, :edit, :update, :destroy, :create, :update, :busca_orcamento, :busca_orcamento_status]

  # GET /orcamentos
  def index
    @orcamentos = Orcamento.all
  end

  # GET /orcamentos/1
  def show
  @pecaa = PecaOrc.new
  @servico_orc = Servico.all
  @pecas_orc = Peca.all
  end

  # GET /orcamentos/new
  def new
    @orcamento = Orcamento.new
    @nome = params[:nome_p]
    @cliente_orc = Cliente.all
    @cliente_search = Cliente.new
  end

  # GET /orcamentos/1/edit
  def edit
  end


  # POST /orcamentos
  def create
    if params[:veiculo_id] != nil
    @orcamento = Orcamento.new(orcamento_params)
    @orcamento.valor_total = 0
    @orcamento.user_id = 0
    @orcamento.cliente_id = Veiculo.find(params[:veiculo_id]).cliente_id
    @orcamento.veiculo_id = params[:veiculo_id]
    if @orcamento.save
      redirect_to @orcamento, notice: 'Orcamento craido com sucesso.'
    else
      redirect_to new_orcamento_path, notice: @orcamento.errors.full_messages
    end
    else
      redirect_to new_orcamento_path, notice: 'Veiculo nao informado'
    end
  end

  # PATCH/PUT /orcamentos/1
  def update
    if @orcamento.update(orcamento_params)
      redirect_to @orcamento, notice: 'Orcamento Atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /orcamentos/1
  def destroy
    @orcamento.destroy
    redirect_to orcamentos_url, notice: 'Orçamento criado com sucesso.'
  end

  def busca_orcamento_status

  status = params[:orcamento] [:status]  
  if status != ""
      @orc = Orcamento.where "status = " "'#{status}'"
  else 
    @orc = Orcamento.all
  end
    respond_to do |format|
    format.html 
    format.js 
  end
  end

  def busca_orcamento
    @selec =  params[:orcamento] [:selec]
    nome =  params[:nome]
    if @selec == "Nome"
     str = "status = " "'#{status}'" " and cliente_id in (select cliente_id from cliente_fs where " "nome like " "'%#{nome}%')"
     str2 = "cliente_id in (select cliente_id from cliente_fs where " "nome like " "'%#{nome}%')"
    elsif @selec == "Razao Social"
     str = "status = " "'#{status}'" " and cliente_id in (select cliente_id from cliente_js where " "razao_social like " "'%#{nome}%')"
     str2 = "cliente_id in (select cliente_id from cliente_js where " "razao_social like " "'%#{nome}%')"
    end
    status = params[:orcamento] [:status]  

    if status != "" && @selec != "" #Se os dois for preenchido
    @orc = Orcamento.where str
    elsif @selec == "" && status != "" #Se só status for preenchido
    @orc = Orcamento.where "status = " "'#{status}'"
    elsif @selec != "" && status == "" #Se só nome for preenchido
    @orc = Orcamento.where str2
    else
    @orc = Orcamento.all
  end
  respond_to do |format|
    format.html 
    format.js 
  end
end 
    

  def edit_peca_orc
  @peca_edit = PecaOrc.find(params[:id])
  respond_to do |format|
    format.html 
    format.js 
  end
  end

def edit_serv_orc
  @servico_edit = ServicoOrc.find(params[:id])
  respond_to do |format|
    format.html 
    format.js 
  end
  end


  def status_orcamento_js
  @orc = Orcamento.find(params[:id])
    respond_to do |format|
      format.html 
      format.js 
    end
  end

  def status_orcamento
    status = params[:orcamento] [:status]
    orc = Orcamento.find(params[:id])
    orc.status = status
    orc.save
     respond_to do |format|
      format.html 
      format.js 
    end
  end

  def seta_user
    set_orcamento
    logged_in?
    @orcamento.user_id = @current_user.id
    @orcamento.save
    redirect_back fallback_location: @orcamento
  end

  def seta_desc
    set_orcamento
    @orcamento.diagnostico =  params[:diagnostico]
    @orcamento.execucao = params[:execucao]
    @orcamento.save    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orcamento
      @orcamento = Orcamento.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def orcamento_params
      params.require(:orcamento).permit(:quilometragem, :ocorrencia, :status)
    end
end

app/helpers/orcamentos_helper.rb
module OrcamentosHelper
end

app/views/orcamentos/table/_table_index.html.erb
<% orcamentos.each do |orcamento| %>
      <tr>
        <td class="span2"><%= orcamento.status %></td>
        <td class="span3"><%= orcamento.cliente.cliente_f.nome %></td>
        <td class="span2"><%= orcamento.veiculo.marca %></td>
        <td class="span3"><%= orcamento.veiculo.placa %></td>
        <td class="span3"><%= orcamento.quilometragem %></td>
        <td class="span4">
        <div class="btn-group">
        <button class="btn ">Funções</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">

        <%= link_to 'Relacionar Peças', orcamento %>
        <%= link_to 'Imprimir', report_orc_path(orcamento, :format => 'pdf'), :target => '_blank' %>
        <%= link_to 'Trocar Status', status_orcamento_js_path(orcamento), :remote => true %> 

        </ul>
      </div>
        </td>

      </tr>
    <% end %>

app/views/orcamentos/table/_table_index2.html.erb
<% orcamentos.each do |orcamento| %>
      <tr>
        <td class="span2"><%= orcamento.status %></td>
        <td class="span3"><%= orcamento.cliente.cliente_j.razao_social %></td>
        <td class="span2"><%= orcamento.veiculo.marca %></td>
        <td class="span3"><%= orcamento.veiculo.placa %></td>
        <td class="span3"><%= orcamento.quilometragem %></td>
        <td class="span4">
        <div class="btn-group">
        <button class="btn ">Funções</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">

        <%= link_to 'Relacionar Peças', orcamento %>
        <%= link_to 'Imprimir', report_orc_path(orcamento, :format => 'pdf'), :target => '_blank' %>
        <%= link_to 'Trocar Status', status_orcamento_js_path(orcamento), :remote => true %> 

        </ul>
      </div>
        </td>

      </tr>
    <% end %>

app/views/orcamentos/table/_table_index3.html.erb
<% orcamentos.each do |orcamento| %>
      <tr>
        <td class="span2"><%= orcamento.status %></td>
        <% if orcamento.cliente.cliente_f != nil %>
        <td class="span3"><%= orcamento.cliente.cliente_f.nome %></td>
        <%else%>
        <td class="span3"><%= orcamento.cliente.cliente_j.razao_social %></td>
        <%end%>
        <td class="span2"><%= orcamento.veiculo.marca %></td>
        <td class="span3"><%= orcamento.veiculo.placa %></td>
        <td class="span3"><%= orcamento.quilometragem %></td>
        <td class="span4">
        <div class="btn-group">
        <button class="btn ">Funções</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">

        <%= link_to 'Relacionar Peças', orcamento %>
        <%= link_to 'Imprimir', report_orc_path(orcamento, :format => 'pdf'), :target => '_blank' %>
        <%= link_to 'Trocar Status', status_orcamento_js_path(orcamento), :remote => true %> 

        </ul>
      </div>
        </td>

      </tr>
    <% end %>

app/views/orcamentos/table/status_orcamento.js.erb
$('#modalStatusOrcamento').modal('close')